### PR TITLE
PLUGINRANGERS-234 | Master file refactor step 1: Separated install process + autoloader

### PR DESCRIPTION
**Pull request by davidmolinacano**
Required by:

- https://github.com/doofinder/doofinder-prestashop/issues/234

In order to avoid an excess of require_once statements, I've implemented a very simple autoloader that can read both PascalCase and snake_case names of the files.

I've tested it locally and it apparently works properly. I've tested the following processes:

- Install uploading the ZIP
- Uninstall from the admin
- Indexing
- Reindexing
- Update on save (update and delete)
- Advanced settings
- Feeds

With the latest changes we will get a 100% green in the Prestashop validator, even better than before! 

image

### CODE REVIEW

**Review by sofia-doofinder — APPROVED** [review]
:rocket:

**Review by pedromcp90 — APPROVED** [review]
Really great job! :trophy:

**Review by eduardogomez97 — APPROVED** [review]
Amazing job!!!

**Comment by davidmolinacano** [comment]
Since it's a big refactor I'll wait until Monday to deploy it.

**Pull request merged**
