### PR TITLE
PLUGINRANGERS-234 | Master file refactor step 7: final steps of the refactor (AdminPanelView and FormManager)

### PR DESCRIPTION
**Pull request by davidmolinacano**
Required by:

- https://github.com/doofinder/doofinder-prestashop/issues/234

### CODE REVIEW

**Comment by davidmolinacano** [comment]
**NOTICE** It's advisable to fix translations just before merging (See part 9)

**Review by sofia-doofinder — APPROVED** [review]

**Comment by davidmolinacano** [comment]
**Reminder to myself**: Once reviewed the translations fixes must be applied before merging. In order not to saturate the reviewers with two different things, these will be applied after the review of this part is finished, so part 9 will no longer be needed

**Review by ogomezba — APPROVED** [review]
:rocket:

**Comment by davidmolinacano** [comment]
After talking with @sofia-doofinder we are going to wait until step 9 to add the translations. If something urgent arises, the translations will be included in a separated PR

**Pull request merged**
